# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: /#
title: Prometheus Computing - UAS Group
email: d.banse@prometheuscomputing.com
author: Prometheus Computing
description: > # "Write an awesome description for your new site here. 
  Welcome to the UAS Group landing page. Here we explore ideas and concepts for projects that leverage unmanned arial systems like drones.
copyright: 'Copyright &copy; 2018 Prometheus Computing. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:

